# Generated by Django 5.2.4 on 2025-07-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_socialevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialEvent',
        ),
    ]
