# Generated by Django 5.2.4 on 2025-07-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_socialevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='SelectedDesign',
        ),
    ]
